version: "3"

services:

  www:
    build: ./docker/www
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - php_ruby

  php_ruby:
    build: ./docker/php_ruby
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db


  db:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - ./.volumes/db:/var/lib/mysql

